# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/13cba194-1b8f-44e8-9816-8d3bd0158a23";
      fsType = "ext4";
    };

  # fileSystems."/boot/efi" =
  #   { device = "systemd-1";
  #     fsType = "autofs";
  #   };

  # fileSystems."/config" =
  #   { device = "systemd-1";
  #     fsType = "autofs";
  #   };

  fileSystems."/config" =
    { device = "/dev/disk/by-uuid/3A7E-6BC6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/3A7E-C31A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
